# By default pass to deployments 
replicaCount: 2

image:
  repository: docker.example.com
  name: checkbuild
  tag: latest
  pullPolicy: IfNotPresent

# Defaults, use Jenkinsfile to map it
namespace: default
ingressUrl: k.example.com

# Just defaults, remap it over set-env
service:
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: "1"
  #   memory: 4Gi
  # requests:
  #   cpu: "1"
  #   memory: 2Gi

nodeSelector: {}

tolerations: []

affinity: {}
